<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVnRDyLm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVnRDyLm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVnRDyLm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVnRDyLm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVnRDyLm\App_KernelDevDebugContainer([
    'container.build_hash' => 'VnRDyLm',
    'container.build_id' => 'c6784d80',
    'container.build_time' => 1709389891,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVnRDyLm');
